### ISSUE TITLE
Delete destination collection when source collection is deleted ?

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-signer#114]
- Create 10 records
- Sign
- Delete source collection
- Re-create source collection
- Create 10 records
- Destination has now 20 records.

**Comment by Natim** [comment]
Even if you delete the records correctly:

* Create 10 records http POST /addons/records
* Sign
* Delete records http DELETE /addons/records
* Sign
* Records are still present in the remote collection.
