### ISSUE TITLE
Use the default rather than force Conf redundancy

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto-signer#151]
Right now you need to be very explicit when using multiple signer backend setup.
We could use the heartbeat one as default and just override the settings that needs to be different.

See https://github.com/mozilla-services/puppet-config/pull/2399

**Comment by leplatrem** [comment]
We read the settings from the `load_from_config()` function. With the current code, if we don't specify the backend setting using `bid_cid` the prefix value is empty and we cannot know which resource we are referring to.

ex:
```ini
signer.autograph.server_url = http://localhost
signer.sb1.autograph.hawk_id = alice
signer.sb1_sc1.autograph.hawk_secret = a-secret
```

I admit it's not super convenient, but wouldn't say it's a bug...
