### ISSUE TITLE
canonical_json is weird

### ISSUE THREAD

**Issue by glasserc** [Kinto/kinto-signer#167]
`canonical_json` doesn't handle iterators, which is the "normal" return type when using kinto-client in Python 3. Right now we've worked around it by just casting to `list`. `canonical_json` should probably handle iterators instead to eliminate a footgun.

Also, `canonical_json` does a deepcopy, but it isn't really clear why.

**Comment by Natim** [comment]
> Also, canonical_json does a deepcopy, but it isn't really clear why.

I guess that's because of `sorted()` that used to be `.sort()` I guess.

**Comment by glasserc** [comment]
A shallow copy is sufficient if you're doing `.sort()`.
