### ISSUE TITLE
Can be done complete the transaction, isolation operations, can be rolled back?

### ISSUE THREAD

**Issue by lvsenlin** [Kinto/kinto-signer#173]
As the title

**Comment by leplatrem** [comment]
I'm sorry but I don't understand the question :(

Basically, the transactions are rolled back if the resulting response status is > 500 or if it is explicitly rolled back like [it is done here](https://github.com/Kinto/kinto-signer/blob/382e45917002f6cc8b0b1d0f2528292c3f85c27b/kinto_signer/listeners.py#L24-L28) when a status is not allowed for example.
