### ISSUE TITLE
Should we check if user is member of reviewers to resign a collection?

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-signer#233]
If the collection is `signed`, and we set to `to-sign`, the server will just refresh the signature.

We have a *refresh signature lamdba* that refreshes signatures periodically.

For our «self-service use case», it is very annoying to be obliged to add the lambda user (eg. `ldap:cloudservices_kinto_prod`) to every `{cid}-reviewers` groups.

Maybe we could skip the group membership verification for this particular «refresh signature» case. Technically the content is already reviewed, we just want the server to refresh the signature. A write permission on the collection metadata should be enough, no?

Alternatively we could add a new setting to statically specify the default group members when automatically created, but I'd rather go with the former approach. 

@glasserc thoughts?

**Comment by bqbn** [comment]
Curiously, when the lambda refreshes signatures, which user does it use to authenticate to the server? If it's `ldap:cloudservices_kinto_prod`, wouldn't it mean the user still needs to be in a proper group to have the proper permissions to do that?

**Comment by leplatrem** [comment]
Yes, the user would still require to be among the ones allowed to `write` the collection metadata. That's already the case for our `ldap:cloudservices_kinto_prod`, since the reviewers are allowed to write: https://github.com/mozilla-services/cloudops-deployment/blob/65c99ca14be844fb283fcf9e27b50dfd5c441e98/projects/kinto/puppet/yaml/permissions/kinto.prod.yaml#L959-L961

**Comment by glasserc** [comment]
I agree that it shouldn't be necessary to be a reviewer to trigger a rereview, but sufficient to be able to write to the source collection metadata.

But I didn't understand the context here. Are we going to stop adding ldap:cloudservices_kinto_prod to the reviewers group or not? If so, then how will the lambda have write permission on the source collection metadata?

**Comment by leplatrem** [comment]
In our context, `ldap:cloudservices_kinto_prod` already has write permissions to the bucket (and thus to every current and future collections)
https://github.com/mozilla-services/cloudops-deployment/blob/23c03ed48693de3a672f5fa7413bc4901a257e9e/projects/kinto/puppet/yaml/permissions/kinto.prod.yaml#L1175-L1181

**Comment by glasserc** [comment]
OK, I see. I hadn't realized we were going to use `/staging/{collection}` for everything. Thanks.
