### ISSUE TITLE
Change the resources settings to be more explicit

### ISSUE THREAD

**Issue by almet** [Kinto/kinto-signer#35]
@natim and @leplatrem expressed the fact that it would be better to define resources as `/buckets/mybucket/collections/mycollection` rather than `mybucket/mycollection` in the settings.

To ponder, I made this choice because you need to specify the **couple** of source/destination resources, which would be a bit too chatty for me.

```ini

sourcebucket/sourcecollection;destinationbucket/destinationcollection
sourcebucket/sourcecollection2;destinationbucket/destinationcollection2
```

With the proposed change, the ini file would look a bit long to me (but that might not be an issue).

```ini

/buckets/sourcebucket/collections/sourcecollection;/buckets/destinationbucket/collections/destinationcollection
/buckets/sourcebucket/collections/sourcecollection2;/buckets/destinationbucket/collections/destinationcollection2
```
I actually like the idea to have more standard ways to define our locations, so this verbosity might be the price to pay :)

**Comment by almet** [comment]
@leplatrem it seems that you're doing the same thing in the `kinto-attachment` plugin. If we are to change this, we probably should change it everywhere.

```ini
kinto.attachment.folder = {bucket_id}/{collection_id}
```

The mode I look at this the more I think it doesn't really make sense to change it (as it seems easier to configure with the bucket/collection rather than the full resource — Let's be honest, you'll write it by hand anyway).

**Comment by leplatrem** [comment]
The `folder` setting is not a reference to a collection in a bucket, it's a pattern for a folder name! The value could be `{bucket_id}-{collection_id}` or whatever. This is unrelated IMO.

In the case of kinto-signer, I still strongly believe that we should use the URI. 

For example we can even imagine to specify filters in the source:
`/buckets/sourcebucket/collections/sourcecollection?enabled=true;/buckets/destinationbucket/collections/destinationcollection`

**Comment by almet** [comment]
> The folder setting is not a reference to a collection in a bucket, it's a pattern for a folder name! The value could be {bucket_id}-{collection_id} or whatever. This is unrelated IMO. In the case of kinto-signer, I still strongly believe that we should use the URI. 

Great, let's go that route.
