### ISSUE TITLE
Should we let autograph choose the hashwith algorithm?

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto-signer#49]
Currently we are asking autograph for a `sha384` signature.

If the response to the question is a yes, then we need to support multiple hash algorithm in the local verifier.

**Comment by almet** [comment]
We should definitely let autograph chose the hashing algorithm to use :-) Currently the local verifier [only handles `sha384`](https://github.com/Kinto/kinto-signer/blob/master/kinto_signer/signer/local_ecdsa.py#L70)

**Comment by jvehent** [comment]
```python
    hashfunc = hashlib.sha384  # default
    if "hash_algorithm" in sigresp[0]:  #you may want to iterate over sigresp
        if sigresp[0]["hash_algorithm"] == "sha256":
            hashfunc = hashlib.sha256
        if sigresp[0]["hash_algorithm"] == "sha512":
            hashfunc = hashlib.sha512
    vk.verify(sigdata, inputdata, hashfunc=hashfunc, sigdecode=ecdsa.util.sigdecode_string)
```
