### ISSUE TITLE
Example with kinto.js

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-signer#53]
I remember that you had a working example with kinto.js using hooks and signatures.
@almet could you please put in the `examples` folder or paste it here so that we can demo the whole thing?
Thanks a lot :)
(*even if it is tight to Gecko, I would still be interested* :))

NB: this issue was originally tracked at https://github.com/Kinto/kinto.js/issues/157

**Comment by leplatrem** [comment]
I found the Gist https://gist.github.com/almet/f4fec4d259f320e52a64

**Comment by almet** [comment]
Yes, it's this one :)

**Comment by leplatrem** [comment]
We could document how to use WebCrypto to verify the signature.
Originally tracked here: https://github.com/Kinto/kinto.js/issues/157

**Comment by almet** [comment]
I'm not sure with the latest changes of the signature protocol, but https://github.com/diafygi/webcrypto-examples#ecdsa---verify is a good resource.

**Comment by leplatrem** [comment]
Se also : http://almet.github.io/cryptojs/
