### ISSUE TITLE
How is -0 serialized ?

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-signer#56]
I can see here https://reviewboard.mozilla.org/r/45459/diff/1#index_header that the following code was
introduced in the client:

```js
if (source === 0) {
  return (Object.is(source, -0)) ? "-0" : "0";
}
```

However, it does not seem to be case here in kinto-signer.

```python
>>> from kinto_signer.serializer import canonical_json
>>> canonical_json([{"id": 1, "a": -0}])
'[{"a":0,"id":1}]'
```

Which one is right ?

/cc @almet @n1k0 @Natim

**Comment by almet** [comment]
This comes from [the json serialization IETF draft](http://webpki.org/ietf/draft-rundgren-predictable-serialization-for-json-tools-00.html#rfc.section.2.2.3).

In python, -0 is strictly equal to 0, but it's not true for `0.0` and `-0.0`. I found this resource quite interesting about this: http://stackoverflow.com/questions/1986152/why-doesnt-python-have-a-sign-function

**Comment by leplatrem** [comment]
Closing in favor of #65
