### ISSUE TITLE
Remove (or improve if mandatory) the resources infos from capabilities

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-signer#63]
![capture d ecran de 2016-04-19 16-02-58](https://cloud.githubusercontent.com/assets/546692/14641791/35e9eee8-0648-11e6-920c-ec0ee86f637a.png)

**Comment by leplatrem** [comment]
Related #35

**Comment by Natim** [comment]
This resource list is just an information about the buckets and collections that are being whatched by the kinto-signer plugin.

This information is quite useful to make sure the service is correctly configured.

**Comment by leplatrem** [comment]
> This information is quite useful to make sure the service is correctly configured.

Ok but then we should use the output of `utils.parse_resources()` instead. `{"bucket": "staging", "collection": add-ons"}`

**Comment by Natim** [comment]
Yes good idea
