### ISSUE TITLE
Validate the public key using x5u

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-signer#68]
> @Natim: I'd like to use the x5u parameter if present to validate the public_key is valid.

**Comment by Natim** [comment]
This might be useful for that: https://gist.github.com/jvehent/d60cde341f9ebb66843e452200c148be

**Comment by Natim** [comment]
According to @jvehent the first cert of the x5u file should be the signing certificate.

**Comment by leplatrem** [comment]
We implemented this in a lambda:

https://github.com/mozilla-services/amo2kinto-lambda/blob/347075c1c5763ae2e05a2ddb0a407a84446bcf7c/aws_lambda.py#L103-L120

Plus, Julien told us that they also have their bunch of scheduled validation jobs...

I guess that this does not truely belong to kinto-signer. Please re-open if I'm wrong
