### ISSUE TITLE
tracking-protection-lists is permanently in `to-resign`

### ISSUE THREAD

**Issue by glasserc** [Kinto/kinto-signer#743]
I'm not sure what happened here. It seems like it was signed in September 18th, and the cert that it was signed with just expired today. It looks like the `workspace` collection never got data in it. I'm not sure if this is why it got stuck.

**Comment by glasserc** [comment]
`cfr-srg` is in the same status.

**Comment by leplatrem** [comment]
This is discussed here https://bugzilla.mozilla.org/show_bug.cgi?id=1582766
