### ISSUE TITLE
Timestamps of records on destination

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-signer#779]
The fact that we keep the original timestamps when approving changes causes issues with kinto-changes (and integration with Push server).

Example of timeline:

- 06:00  changes edited in `cid1`
- 06:01  review requested in `cid1`
- 09:00  changes edited in `cid2`
- 09:01  review requested in `cid2`
- 09:30 changes approved in `cid2`
- 09:30 kinto-changes is updated and Push received timestamp 09:00

- 12:00 changes approved in `cid1`
- 12:00 kinto-changes is updated and Push received timestamp 06:00

The kinto-changes collections becomes this:
- ETag 09:00
- records: 
  - `cid2`: 09:00
  - `cid1`: 06:00

Which is wrong! The `cid1` was updated after `cid2`.

**Comment by glasserc** [comment]
This is certainly bad...

Here are some desirable properties of the system from my point of view:

- Records "pushed" from a source collection to destination collections should have the same timestamp in both places
- Resource timestamps should be monotonic and not change unnecessarily
- kinto-changes should not have any state, which implies:
    - records in the monitor/changes collection do not have a timestamp "unto themselves" but just reflect another existing timestamp elsewhere

The proposed fix breaks the first one of these. I think we have to break at least one, and I'm OK with it being the first one. However, what about the second one? I don't really understand the semantics of resource timestamps so maybe there's an obvious reason why this wouldn't work, but maybe we could bump the collection timestamp during the push somehow. We don't have an API to do that in the current storage API that I can tell, so this might be a bigger, messier change than we want.

As a related thought experiment, let's say the following happens using garden-variety core Kinto:

- 06:00 post a new record to `cid`
- 06:01 get `cid` -- resource_timestamp is 06:00
- 06:02 post a record to `cid` with `last_modified` of 05:59
- 06:03 get `cid` -- resource_timestamp is still 06:00!

I think this is analogous to what we're doing with the kinto signer code and I think it's bad in kinto core too. I think resource_timestamp just being "the biggest timestamp of any of the resources" is inherently flawed and we should move instead to "the last timestamp any resource changed" instead. I think that would solve this problem too.
