### ISSUE TITLE
Configure records filters from source to preview/destination

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto-signer#81]

**Comment by leplatrem** [comment]
Can you describe what you mean here ?

**Comment by Natim** [comment]
I mean records with ``enabled: false`` should not be present nor signed in the destination collection.

**Comment by leplatrem** [comment]
I propose that we add filtering in configuration:

`/buckets/source/collections/collection1/records?enabled=true;/buckets/destination/collections/collection1`

**Comment by Natim** [comment]
Interresting...

**Comment by leplatrem** [comment]
@Natim we don't have this use-case anymore at Mozilla. I would like to close it. Please reopen if necessary :)
