### ISSUE TITLE
Improve resources configuration 

### ISSUE THREAD

**Issue by tarekziade** [Kinto/kinto-signer#88]
The configuration for kinto.signer.resources is hard to read and makes it super easy to make typos (we did) - and nothing prevents the signer to catch them

what about this  

```
kinto.signer.resource.one = staging/foo , target/foo 
kinto.signer.resource.two = staging/baz , target/baz 
kinto.signer.resource.three = staging/boh , target/boh 
```

with one extra verification: if the split(',') can't produce 2 elements that are URL sub paths we raise a blocker error

**Comment by leplatrem** [comment]
Related #69

**Comment by Natim** [comment]
How is this different from:

```
kinto.signer.resources =
        staging/foo ; target/foo 
        staging/baz ; target/baz 
        staging/boh ; target/boh 
```

**Comment by phrawzty** [comment]
Please be aware that in the svcops environment, the templates that build the `ini` files are populated from a basic key / value lookup. As a result, multi-line values require interpolation, and that makes me nervous. If there's a sane way to stick with a simple, single-line `var = value` syntax, that'd be preferable.

Fwiw, `kinto.signer.resource.<one|two|...> = <value>` is a reasonable compromise.

**Comment by tarekziade** [comment]
In any case, let's verify that we do have tuples of 2 PATHs elements or raise an error

**Comment by leplatrem** [comment]
we could use ``=>`` instead of ``;`` to show the worklfow

c.f. https://github.com/Kinto/kinto-signer/pull/127#discussion_r81127671

**Comment by leplatrem** [comment]
There would be a need also to specify editors/reviewers group by resource
